# Generated by Django 4.2.19 on 2025-02-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网站名称')),
                ('domain', models.CharField(max_length=100, verbose_name='域名')),
                ('port', models.IntegerField(default=80, verbose_name='端口')),
                ('php_version', models.CharField(max_length=10, verbose_name='PHP版本')),
                ('path', models.CharField(max_length=255, verbose_name='网站目录')),
                ('ssl', models.BooleanField(default=False, verbose_name='SSL状态')),
                ('status', models.BooleanField(default=True, verbose_name='运行状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站',
                'verbose_name_plural': '网站',
                'ordering': ['-created_at'],
            },
        ),
    ]
