# Generated by Django 4.2.19 on 2025-02-23 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websites', '0003_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True, verbose_name='会话ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('status', models.CharField(choices=[('active', '活动'), ('closed', '已关闭')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='最后活动时间')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='进程ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '终端会话',
                'verbose_name_plural': '终端会话',
                'ordering': ['-created_at'],
            },
        ),
    ]
