# Generated by Django 4.2.19 on 2025-02-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_website_nginx_config_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='ssl_certificate_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SSL 证书路径'),
        ),
        migrations.AddField(
            model_name='website',
            name='ssl_key_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SSL 私钥路径'),
        ),
        migrations.AddField(
            model_name='website',
            name='ssl_provider',
            field=models.CharField(choices=[('none', '不使用 SSL'), ('cloudflare', 'Cloudflare'), ('letsencrypt', "Let's Encrypt")], default='none', max_length=20, verbose_name='SSL 提供商'),
        ),
    ]
